[package]

name = "dnskit-resolver"
description = "DNSKit Resolver"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true


[dependencies]

dnskit-lib = { path = "../../lib" }
anyhow.workspace = true
async-trait.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
tokio.workspace = true
hex.workspace = true
clap.workspace = true
